### ISSUE TITLE
Bug on restoring migration log

### ISSUE THREAD

**Issue by wastene** [iotaledger/seed-migration-tool#5]
##### Bug Finding: -> debugging leads to the following line in the source code
https://github.com/iotaledger/seed-migration-tool/blob/master/src/views/Status.svelte#L170

#### Assumption:

```javascript
 data.key.split(',').length && !data.key.split(',').every(Number)
```
First part checks if not empty; Second part checks if all given number in the key are actually numbers

#### Code to reproduce the problem 

```javascript
 var json = '{"key": "255,1,23,12"}';
 var data = JSON.parse(json);
 var numbers = data.key.split(",");
 console.log(numbers.length);   
 console.log(numbers.every(Number));
```  
```cmd
 > 4
 > true
```  

If a `0` (zero) is in the key though the if statements' logic fails

```javascript
 var json = '{"key": "255,0,23,12"}';
 var data = JSON.parse(json);
 var numbers = data.key.split(",");
 console.log(numbers.length);   
 console.log(numbers.every(Number));
```  
```cmd
 > 4
 > false
```  
##### Suggestion
Alternative check for all characters given are `numbers`. So another check for `.every(Number)` is needed, that is also taking `zeros` into account

**Comment by wastene** [comment]
@cvarley100 pr #7 don't fix it. 
Now you need to remove the Not Operator "!", because .some(isNaN) returns True if any number in the list is NaN, which results to false.

And if in the list any number is not a number, the if condition is not true and the error is not called. On the other hand, if all numbers in the list are numbers, some(isNaN) returns False, which results to True and so the if-condition holds and throws the error, which is not correctly

**Comment by cvarley100** [comment]
@wastene See https://github.com/iotaledger/seed-migration-tool/pull/8
